### ISSUE TITLE
Why are three syntaxes for lists necessary?

### ISSUE THREAD

**Issue by v217** [NeowayLabs/nash#112]
More a question than an issue.
In the spec.ebnf you have three syntaxes for lists:
{} Braces for lists of statements (eg. line 44) and
() parentheses for lists (line 72)
( , , , ) parentheses with commas for function argument lists (line 50)

Perhaps I am missing something? Wouldn't it be better to have as few as possible builtin syntax/special characters.

**Comment by tiago4orion** [comment]
mainly for code readability, otherwise we have lisp-like syntax.

**Comment by v217** [comment]
Apart from code readability what are the other reasons? The simpler the syntax the fewer the characters/constructs you have to escape in commandline tools. Recent commandline tools like GNU parallel, find etc ... already now show the limit of what's possible and needed, but could be much simpler. Apart from that a smaller implementation is easier to maintain and safer.

**Comment by tiago4orion** [comment]
I agree that implementation could be much simpler, but disagree about safety.
In the majority of POSIX shells out there, the syntax of the shell could be confused with command line argument syntaxes (e.g.: awk syntax confused with bash syntax). For the reader, it's hard to disambiguate. 

In this specific case, using the same syntax for lists, function parameters and code blocks will not solve your problem with the other syntaxes of commands.

Relaxing the shell syntax to something like Scheme have lots of good benefits, but none is in my goals.

My goal with nash is safety of scripts, readability and tooling (code analysis). If the code runs without error, then probably it's correct. The focus is on the nash syntax being completely separate, it's created in a way that is simpler to format the code and analyze nash scripts by tools. Having other syntaxes quoted, like "awk" or "parallel" syntaxes, make very easy to analyze the correctness of nash syntax AND awk, parallel, perl, etc, quoted syntaxes... 

Trade off is readability and safety versus simple implementation and easy of embedding other syntaxes. 

But in essence, you cannot have readability with gnu parallel and awk syntaxes and perl regexes not quoted...

Look at the code below:

```sh
awk {print}
```
If the shell is bash, then it's a valid awk invocation passing "{print}" as first argument. The AWK syntax must be passed as first argument, then you must quote or write it without spaces in it... If you put a simple space in-between (like awk { print }) then awk will fail to parse their own syntax.. In nash, it's a parser error that may be caught by your editor when trying to fmt your code (nashfmt). 

In case of parallel, it was designed to work with bash, zsh and csh shells, then it get its syntax from multiple arguments (not requiring quotes in most cases), but in the same way shell syntax still must be quoted. Eg.:

```sh
# wrong
$ parallel echo Job {#} of {= $_=total_jobs() =} ::: {1..5}
# right
parallel echo Job {#} of {= '$_=total_jobs()' =} ::: {1..5}
```
The lack of strict separation between shell and other syntaxes is the reason why there's so few toolings around shells.

Look at the example below:

```sh
λ> cat buggy.sh
#!/usr/bin/env nash
cat file.txt | awk "{print $1,$5"
λ> nash-analyze ./buggy.sh
nash syntax: OK
AWK syntax: Error at 2:33: unexpected newline or end of string
```
This tool can analyze nash scripts and report common errors without executing the code. Even few surprises in production... The tool `nash-analyze` don't even exist yet, but it's on my TODO list.

I'm not against change the nash syntax, it have subtle problems that needs work. But I dislike the idea of relaxing it to avoid escape other syntaxes inside it.
If you think it could be improved (having the goals I said above in mind), then submit a proposal for the syntax change with a set of usage examples that clarify the benefits and we can discuss it =)
