### ISSUE TITLE
How to bindfn and pass a parameter

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/nash#115]
I have this to configure my vpn:

```
fn vpn(subcommand) {
    sudo systemctl $subcommand openvpn@client.service
}

bindfn vpnstart vpn("start")
bindfn vpnstop vpn("stop")
```

Sadly it wont work (it was intuitive to me that it could). The error:

```
Multi-line command not finished. Found STRING but expect ')'
```

Is there a way to so something like this ?

**Comment by tiago4orion** [comment]
Interesting. I'd not thought of that use case.

But first, the arguments are reversed. You must use `bindfn` to bind a function to some command name. But anyway, it'll not work to bind a function with a default argument. I liked the idea.

You can make it work today with a helper function.

```sh
λ> fn vpnstart() { vpn("start") }
λ> fn vpnstop() { vpn("stop") }
λ> bindfn vpnstart vpnstart
λ> bindfn vpnstop vpnstop
```

**Comment by katcipis** [comment]
Yeah I got the order wrong and fixed later :-)

I'm thinking if it makes sense, because actually bindfn binds a function to a name, vpn("start") is not a function, is a function call, what I was trying to use resembles more a macro, when "name" is resolved paste this whole chunk of stuff on its place. Perhaps bindmacro ? :-). To be honest, your solution seems good enough and is less complex than having the notion of macros (just old habits that die hard).

I got the order wrong because on my head it makes more sense to bind the name to a function. Again, old habbits from macros + languages like Lua, where you bind the name to the function (from left to right), like:

```Lua
a = functio(a,b)
end
```

Go works the same way:

```Go
a := func() {
}
```

But I'm sure you got the idea from some place and it also makes sense in some way :-).

**Comment by tiago4orion** [comment]
Yeah, the idea of bindfn is the reverse, bind a function name to a command name. Bindfn idea comes from the beginning of nash, when I started to create helper functions to improve my interactive use, but had to invoke the functions in the verbose way (eg.: gcheck("feat/10")).
