### ISSUE TITLE
Proposals for new IFS implementation

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#128]
It's very annoying that your command assignment depends on a external variable be set. It's error prone and can break in unexpected ways.

Because everyone can set a default value for IFS in their init, the scripts should always be careful and set a proper value before any command assignment. 

There are two ways I can think of to solve this problem. Remove IFS entirely or make it scoped.
## No IFS (No split by default)

_backward incompatible_

This way, every command assignment will always return a string and we'll need a built in function to split it explicitly into a list:

``` sh
val <= cat data.csv | grep -v "header" # $val store entire string
val <= split($val, ("\n")) # Split data into a list and store in $val
```
## Scoped IFS

_backward compatible_ 

Using IIFE (immediately-invoked function expression):

``` sh
val <= fn () {
        IFS = ("\n")
        ret <= cat data.csv | grep -v "header"
        return $ret
}()
```

It`s not supported yet, but easy to implement and works, but as this kind of assignment occurs very often, we need a shorter way...

Maybe a built in `split` command in the pipe:

``` sh
val <= cat data.csv | grep -v "header" | split "\n"
```

But it must be the last component of the pipeline...

Maybe improve the syntax to support scoped variables in statements:

``` sh
val <= (echo $path) path = $PATH
val <= (cat data.csv | grep -v "header") IFS = ("\n")
```

I cannot think of a better way to improve the syntax to support scoped variables...  Maybe someone could help.

@katcipis @lborguetti 
Ideas?

**Comment by katcipis** [comment]
I like the no IFS idea...still cant see one single advantage of it besides being hard to understand and implicit

**Comment by ppizarro** [comment]
I like the no IFS idea too.
I love the split command.
It's explicit and reinforce the unix way.

**Comment by tiago4orion** [comment]
Thanks!

The IFS was removed in #139 but I'll create the release v0.1.4 before apply the merge. As it's a backward incompatible change, every other nash script must be updated too. I'm thinking in a way to make the change painless. A tool to fix old scripts is easy to do, but I don't know worth the effort as we have few scripts to update.

**Comment by ppizarro** [comment]
Nice.

And what about the split command?

What's happen if the split is executed passing "\n" and it receives an infinite data stream without a '\n'?

The split command should be a maximum value for the buffered data. Maybe it can be passed as an argument.

**Comment by tiago4orion** [comment]
I'm not sure what you mean by that, but if you're talking about split being used in pipes, it'll not work.

The split function works like `strings.Split` of Go. It always returns a list and first parameter is the entire content to be splited. 

I'm thinking about ways to make it works with pipes, but there's some inconsistencies because pipes works with data streams and split returns a object list.

**Comment by ppizarro** [comment]
Sorry, I did not explain my question right.
I'm talking about it works with pipes.

**Comment by katcipis** [comment]
@ppizarro from what I understood the split of nash works on a string, not a stream. It is like receiving a string parameter instead of a io.Reader on Go. So your case does not seem to be possible.
