### ISSUE TITLE
Setenv is boring 

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#133]
@katcipis

**Comment by katcipis** [comment]
Could not agree more :-)

Something like this:

```
setenv AZURE_TRETA "value"
```

Is possible ? Like a function with two parameters ? (sorry for the extreme ignorance).

Or even implement export as an alias :-)

**Comment by tiago4orion** [comment]
`setenv AZURE_TRETA "value"` does not transmit the idea that AZURE_TRETA will be equal "value" when exported..

I'd rather something like:

`setenv AZURE_TRETA="value"`

**Comment by katcipis** [comment]
I thought you would not like to parse the "="...I like this option...but if we are going on this path....why not export ? People in general are VERY used with export :-)

**Comment by tiago4orion** [comment]
What we're trying to achieve? Set an environment ... For me `export` brings the idea of `export`ing the name, and it's not what the command will do.. Nash export by default every variable declared outside the scope of functions.

but I'm happy with `export` too if you prefer. But nash is sufficiently different from other shells..

**Comment by katcipis** [comment]
What would be to "export a name" ?

**Comment by tiago4orion** [comment]
file 1.sh

```sh
exportedName = "something"

fn a() {
        notExportedName = "some other thing"
}
```

file main.sh

```sh
import ./1.sh
echo $exportName # works
echo $notExportedName # fail, variable not declared
```

**Comment by katcipis** [comment]
This sounds more to me like basic lexical scoping than exporting stuff :-). Actually never saw the export thing outside of shell, I don't think it is awesome...but it is a very common name used on shell scripts...not sure what we get having something with the same semantics but with a different name. Anyway, no strong feelings about this

**Comment by tiago4orion** [comment]
You are right, it sounds like scoping, but I'm not sure because are only two kinds (global and function scope)

- global scope: Everything declared outside a function
- function scope: Everything declared inside a function

There's no scope for `if`, `for`, etc, because the only difference with functions is that it's a `subshell` (another limited instance of nash that has a parent shell).

What I was trying to say is that when you import some file in nash you merge the global scopes.

About the keyword name to set the environment, I'm trying to avoid the `export` name because of our talk some days ago about implementing a module/package system to nash... and if it turns to be real, then `export` could makes sense for making a `name` public.

**Comment by katcipis** [comment]
Let's talk in person about this one :-)

**Comment by tiago4orion** [comment]
@geyslan @katcipis @lborguetti 

What do you guys think of the following spec change:

From:

```
/* Set environment variable */
setenvDecl = "setenv" identifier .
```

to:

```
/* Set environment variable */
setenvDecl = "setenv" (identifier | varDecl) .
```

Where `varDecl` is already declared [here](https://github.com/NeowayLabs/nash/blob/master/spec.ebnf#L8):

The name `setenv` is an example, could be `export`.

With this little change, the new syntax for setting a environment var will be pretty powerful and yet backward compatible. 
Valid examples:

```sh
setenv PATH # current implementation

setenv PATH = "/bin:/usr/bin"

setenv PATH <= getpaths()

setenv PATH <= (
        echo $locations | tr ";" ":"
)
```

Makes sense? As varDecl parser is already done and stable, the change will be very easy. Apart from that, this new way could have great benefits. Or no?

**Comment by geyslan** [comment]
In advance I liked your proposal to improve the assignment of a variable (varDecl).

After reading the entire thread these are my thoughts and doubts.

- I wouldn't like much to `import` (source) a script and automatically get global scoped variables available into importer context. Thus I would prefer to use a keyword like `export` letting my intent clear instead.
- The **ebnf** `(identifier | varDecl)` will make possible a combined assignment? Eg.
```shell
setenv PATH <= getpaths() + (echo $locations)
```
- And about constants combined with cmd outputs, is it already possible?
```shell
setenv PATH = "/bin:/usr/bin" + getpaths()
```

**Comment by tiago4orion** [comment]
> I wouldn't like much to import (source) a script and automatically get global scoped variables available into importer context. Thus I would prefer to use a keyword like export letting my intent clear instead.

I agree with you, but I'd to say that current nash `import` keyword works like `source` in posix or bash. Then, it's designed to get global scoped variables in. When nash get modules supported, we can improve that in some way.

> The ebnf (identifier | varDecl) will make possible a combined assignment? Eg.
no

Nash string concatenation only works with literal strings, arguments and variables.
https://github.com/NeowayLabs/nash/blob/master/spec.ebnf#L96
The spec is outdated regarding `args`...

This could get added in the future because it's backward compatible and makes sense. There's lots of useful syntax constructs still missing in nash.

**Comment by katcipis** [comment]
@tiago4orion this is GOOD SHIT :-). Perhaps changing the name from export will make it more clear that it is more awesome than shell export

**Comment by tiago4orion** [comment]
Thanks! 

Change merged.
