### ISSUE TITLE
Disable binds made with 'bindfn' when running in non-interactive (script) mode 

### ISSUE THREAD

**Issue by vitorarins** [NeowayLabs/nash#150]
Running `nash` in non-interactive mode with binds enabled could be dangerous when running a script in different servers. `nash` was always guaranteed to run real commands instead of binds, but that will probably change in the future with #151.

**Comment by katcipis** [comment]
Not sure if this makes sense. It seems that you are moving the problem of "my servers are different" to nash. Guaranteeing a set of equal servers (same config and binds) is not a nash problem.

I could build a set of servers with automation that have a lot of awesome bindfn on them...why would I have my bindfn disabled automatically in that case ?

**Comment by tiago4orion** [comment]
@katcipis What's the advantage of using a bindfn in a script?

Why not use a function ?

**Comment by vitorarins** [comment]
Good point.

One more problem that I forgot to add to the description: @tiago4orion brought up the question of obfuscating code. A bind of type: `bindfn malicious_function ls` could be add in a server. And when you use `ls` in your script, an unknown function will be executed.

**Comment by katcipis** [comment]
What about a malicious binary beng injected on the server ? Or overriding the PATH variable ? Still don't seem like a good idea to me.

**Comment by vitorarins** [comment]
IMO the idea is still valid in a security point of view. But maybe we should discuss the usability like suggested by @tiago4orion. Why would someone prefer to use `foo stuff` instead of `foo("stuff")` in a script?

**Comment by katcipis** [comment]
I think it is not exactly about why I would use the bindfn or not, it is about uniformity and predictability. It seems reasonable for me to expect that when a execute a shell script from a shell, the shell script does inherit the context of the parent shell, like environment variables. It seems to be that is the same as resetting environment variables because it could be dangerous to allow this because someone could have injected something dangerous.

And again, it really feels like you have some problems ensuring proper server bootstrap/configuration and want the shell to do stuff for you to try to avoid problems.

But hell, what do I know, do what you guys think its best :-)

**Comment by tiago4orion** [comment]
Bindfn is a feature created to enhance user experience when using nash as a cli (interactive) in daily usage. There's no benefit in scripts (at all). In the very same way, bash *disable aliases* in scripts.

@katcipis You know, from the very beginning I wanted nash scripts to be explicit, readable and reliable. 

But,

1. Enabling binds in scripts is terrible for *readability*.

Example: In case there's no `ag` program in the system, what do the script below?

```sh
#!/usr/bin/env nash
cd /etc
ag root passwd 
```

Currently, to discover that I'll need to dig into the user profile (~/.nash) to find the correct bind. *There's no import*, nothing to help an IDE (or tool) to lookup the symbol `ag`, and so on.

2- Terrible for reliability.

How much scripts can I brake only changing my *~/.nash/aliases/* ?

Another idea could be disabling *init loading (~/.nash)* when executing scripts, but that would create several other problems...

@katcipis Do you know other options to solve the problems above?

**Comment by katcipis** [comment]
If aliases already work the way you described the behavior should not be a surprise to anyone. Sorry for the noise, sounds good to me :+1:
