### ISSUE TITLE
Make binds from `bindfn` have precedence over commands

### ISSUE THREAD

**Issue by vitorarins** [NeowayLabs/nash#151]
This depends on #150.

`bindfn` should be used with the idea of overriding commands, so when you do `bindfn foo_function ls` the new `ls` execution should call `foo_function` instead of the command `ls`.

Right now `nash` will only execute a "binded" function if it doesn't find the equivalent command in the OS. Making it impossible to do what was previously cited.

**Comment by katcipis** [comment]
Makes sense to me :+1:
