### ISSUE TITLE
Could not create containers

### ISSUE THREAD

**Issue by PotHix** [NeowayLabs/nash#219]
I'm using Archlinux with Kernel `4.10.11-1-ARCH`.

I don't have user namespaces available for this kernel:

```
$ zgrep CONFIG_USER_NS /proc/config.gz
# CONFIG_USER_NS is not set
```

When I try rfork, I get an "invalid argument" error.

```
$ sudo /home/pothix/go/bin/nash 

λ> whoami
root
λ> rfork c {
>>> id
>>> }
ERROR: fork/exec /home/pothix/go/bin/nash: invalid argument
```

My GOPATH is `/home/pothix/go` according to the default of Go 1.8.

**Comment by tiago4orion** [comment]
Hello @PotHix 

Sorry for the late reply.
If you don't have user namespaces available in your kernel, then you cannot create unprivileged containers (without root access).
Then, to create containers you'll need root as you need when using docker or rkt.

```
git:(master)λ> sudo su
[root@stay-away geoindexer]# nash
λ> rfork pmnis {
>>> mount -t proc proc /proc
>>> ps aux
>>> }
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 186024  2452 pts/6    Sl+  15:02   0:00 -nashd- -noinit -addr /tmp/nash.JkKt.sock
root         9  0.0  0.0  41032  3352 pts/6    R+   15:02   0:00 /bin/ps aux
λ>  
```

**Comment by PotHix** [comment]
Some more info:

```
# Downloaded the latest binary
[Mordor Downloads] tar xvf nash-v0.5-linux-amd64.tar.gz 
cmd/nash/nash
cmd/nashfmt/nashfmt

# Unpriviledged user
[Mordor Downloads] ./cmd/nash/nash 
λ> whoami
pothix

# Doesn't work as expected
λ> rfork c {
>>> id
>>> }
ERROR: fork/exec /home/pothix/Downloads/cmd/nash/nash: invalid argument
λ> exit

# root user
[Mordor Downloads] sudo su
[sudo] password for pothix: 
[root@mordor Downloads]# ./cmd/nash/nash 
λ> whoami
root

# same thing
λ> rfork c {
>>> id
>>> }
ERROR: fork/exec /home/pothix/Downloads/cmd/nash/nash: invalid argument
```

Am I missing something?

**Comment by tiago4orion** [comment]
The 'c' option stands for container but requires full namespace support (including USER_NS). Take a look in my example, I used "pmnis" that's an abbreviation to pid, mount, net, ipc and uts namespaces.
The `invalid argument` you're seeing is from the kernel clone(2) syscall because the 'c' option uses USER_NS also.. Sorry because this is not fully documented yet.

**Comment by tiago4orion** [comment]
Take a look in the options and the correspondent kernel flag:
https://github.com/NeowayLabs/nash/blob/master/internal/sh/rfork_linux.go#L231

**Comment by PotHix** [comment]
Gotcha. Thanks for clarifying and I recommend improving the readme as soon as possible. :)
