### ISSUE TITLE
interpreter: Fn declarations must use only the variable environment

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#223]
Currently, when you do:
```
fn func() {}
```
Nash interpreter automatically sets a variable name `$func` pointing to the func procedure (subshell). But because of a wrong assumption, declared functions were stored in a different place than variables and a new sh.FnObj object is added in the variable space.

But this leads to the inconsistency below:
```
fn a() { echo "hello" } # declares $a
a = "bleh" # overwrites only in the variable space
a() # Output: hello
echo $a # Output: bleh
```

Why the current implementation?
The wrong rationale was that when evaluating `a()` wouldn't need to get the object variable but just the raw procedure (then stored in a different place).

The solution must be to use only the function object stored in the backed variable.

**Comment by tiago4orion** [comment]
Same happens for builtins:

```
λ> echo $append
ERROR: Function cannot be passed as argument to commands.
git:(fixClosuresBugs)λ> append = "ahhhh"
git:(fixClosuresBugs)λ> echo $append
ahhhh
git:(fixClosuresBugs)λ> b <= append((), "test")
git:(fixClosuresBugs)λ> echo $b
test
```

**Comment by katcipis** [comment]
Yeah this is pretty odd. I like the idea of functions as first class citizens, just handle them like any other value of the language =)

**Comment by ppizarro** [comment]
I think this same issue affects the use of reentrant functions.
Below is an example of an error using reentrant functions:

`
fn iter(first, last, func) {
   sequence <= seq $first $last
   range <= split($sequence, "\n")
   for i in $range {
       $func($i)
   }
}

fn create_vm(index) {
	echo "create_vm: " + $index
	iter("1", "3", $create_disk)
}

fn create_disk(index) {
	echo "\tcreate_disk: " + $index
}

iter("1", "2", $create_vm)
`
This displays the following:
`
create_vm: 1
	create_disk: 1
	create_disk: 2
	create_disk: 3
`

When it should display the following:
`
create_vm: 1
	create_disk: 1
	create_disk: 2
	create_disk: 3
create_vm: 2
	create_disk: 1
	create_disk: 2
	create_disk: 3
`

**Comment by tiago4orion** [comment]
Thanks @ppizarro 
I'll use your example as a test case in the fix.
