### ISSUE TITLE
windows: Use proper env variable to set NASHPATH

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#236]
![image](https://user-images.githubusercontent.com/251478/29523609-f306f84e-8663-11e7-9e35-a086e4a67e6d.png)

To start nash on windows requires setting `NASHPATH` explicitly, but we can use the environment variable `USERPROFILE` or `HOMEPATH`.

**Comment by katcipis** [comment]
The joys of windows support =)
