### ISSUE TITLE
Add login shell mode

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#24]
Currently, nash can only be used as interactive shell. 

Nash doesn't import the /etc/profile and /etc/profile.d files when invoked as login shell because it's not POSIX compliant. When started, the only file loaded is $NASHPATH/.init file. $NASHPATH commonly is ~/.nash/init if not explicitly set.

As nash is a very opinionated shell, it will never interpret POSIX files, but then how login shell can be achieved?

1. Replace your /etc/profile and /etc/profile.d/* with nash compatible profile files.
2. Use an alternate system profile directory for nash login shell. Eg.: /etc/nash.d/profile
3. Create a nash library to convert POSIX profiles to nash profiles before import /etc/profile.

I prefer the second approach, then the only nash changes will be to load the /etc/nash.d/profile when invoked as a login shell (ie when executed with -nash in argv[0]).

**Comment by tiago4orion** [comment]
For now I'm able to use nash as login shell on my personal notebook with arch linux.
But, I'm not loading anything from /etc/profile yet. I'd to set everything required on my ~/.nash/init file.

Apparently, the only required environment variables required to be set is LANG and SHELL. Nash already sets SHELL but when invoked as login shell the argv[0] is set to "-nash" and exporting it as SHELL broke some GUI applications (eg.: dmenu_run).

Below is my complete init file:

```sh
PLAN9  = $HOME + "/projects/plan9/plan9port"
GOPATH = $HOME + "/.gvm/pkgsets/go1.5.3/global"
GOROOT = $HOME + "/.gvm/gos/go1.5.3"
LBIN   = $HOME + "/bin"
PATH   = $PATH + ":/usr/local/bin:" + $LBIN + ":" + $PLAN9 + "/bin:" + $GOROOT + "/bin:" + $GOPATH + "/bin"
SHELL  = $HOME + "/.gvm/pkgsets/go1.5.3/global/bin/nash"
LANG   = "en_US.UTF-8"

setenv SHELL
setenv LANG
setenv PLAN9
setenv GOPATH
setenv GOROOT
setenv PATH




```

**Comment by tiago4orion** [comment]
My current  .nash directory is here: https://github.com/tiago4orion/dotnash

To use nash as login shell, you only need to add nash to /etc/shells, update your /etc/passwd entry to use nash for your user, and then use my dotnash or customize yours based on my last comment.

**Comment by geyslan** [comment]
@tiago4orion, Makefile could link `ln -s` built nash to `/bin/nash` and add it into `/etc/shells`. What do you think?
