### ISSUE TITLE
bug: Failing rfork tests

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/nash#252]
I'm getting this:

```
--- FAIL: TestExecuteRforkUserNS (0.00s)
        shell_linux_test.go:72: fork/exec /home/katz/workspace/go/src/github.com/NeowayLabs/nash/cmd/nash/nash: operation not permitted
=== RUN   TestExecuteRforkEnvVars
--- FAIL: TestExecuteRforkEnvVars (0.00s)
        shell_linux_test.go:107: fork/exec /home/katz/workspace/go/src/github.com/NeowayLabs/nash/cmd/nash/nash: operation not permitted
=== RUN   TestExecuteRforkUserNSNested
--- FAIL: TestExecuteRforkUserNSNested (0.00s)
        shell_linux_test.go:142: fork/exec /home/katz/workspace/go/src/github.com/NeowayLabs/nash/cmd/nash/nash: operation not permitted
=== RUN   TestExecuteIssue68
```

The same code runs on the CI with no problem and it seems to have started since I updated my arch linux x_x, I would guess that something changed on the kernel:

```
(katz)λ> uname -a
Linux archlinux 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux
```

**Comment by tiago4orion** [comment]
I was able to reproduce in a fresh install of arch linux.
After some search, I found that newly kernels require enabling userns at runtime:

```sh
# sysctl -w kernel.unprivileged_userns_clone=1
```
We already detect in tests if user has USER_NS in kernel, but maybe we need to check if /proc/sys/kernel/unprivileged_userns_clone has a value other than zero also.

**Comment by katcipis** [comment]
Seems like the way to go, nothing is linux is ever simple ? =/

**Comment by katcipis** [comment]
Actually we could check just for `sysctl -w kernel.unprivileged_userns_clone=1` no ?

**Comment by tiago4orion** [comment]
I'm going to fix this now because travis tests are not passing anymore because (I think) of this problem.
You mean check if /proc/sys/kernel/unprivileged_userns_clone is equal 1 instead of different than zero? If so, I agreed. Will do that.
