### ISSUE TITLE
Error when GOPATH contains multiple entries (master)

### ISSUE THREAD

**Issue by dragonmaus** [NeowayLabs/nash#272]
When nash is installed from git master (`make install`), it returns the following error if GOPATH contains multiple path entries:
`error[stat /home/dragon/src/go/ext:/home/dragon/src/go/src/github.com/NeowayLabs/nash: no such file or directory] validating nashroot`

Changing GOPATH to a single entry prevents the error, but is not a sustainable solution.

**Comment by tiago4orion** [comment]
What should we do in this case? Use the first gopath directory?

**Comment by dragonmaus** [comment]
@tiago4orion It should ideally follow go's own behaviour; namely, search all entries of `GOPATH` when looking for packages, and use the first entry when writing anything.

**Comment by tiago4orion** [comment]
In this case I think the best thing we can do is avoid look into GOPATH when inferring `NASHROOT`. Then the behaviour will be: look if `NASHROOT` variable is set, if not use `$HOME/nashroot`.
