### ISSUE TITLE
spec: Add support for list of lists

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#92]
```sh
λ> tags = (
	("Name" "Production")
	("Team" "Maps")
)
```

**Comment by tiago4orion** [comment]
Closed by #93

**Comment by v217** [comment]
Not sure if this is a good idea, but
if nested lists are supported, it's perfectly reasonable to support nested IFS.

    IFS=("\n" IFS=(" "))

So the output of ls -la is:


    λ> ls -la
    (
    (total 408)
    (drwxr-xr-x 10 i4k i4k  4096 May 24 12:30 .)
    (drwxr-xr-x 12 i4k i4k  4096 May 17 12:07 ..)
    (-rw-r--r--  1 i4k i4k   406 May 23 17:34 argtype_string.go)
    (drwxr-xr-x  3 i4k i4k  4096 May  4 09:23 cmd)
    (-rw-r--r--  1 i4k i4k  8523 May 24 11:03 cmd.go)
    (-rw-r--r--  1 i4k i4k    13 May 10 09:51 cmd_test.go)
    (...   )
    .
    .
    .
    
    
    )

**Comment by tiago4orion** [comment]
Interesting. 

I'd not thought about it. Maybe make sense using a special `ifs` function for that.
