### ISSUE TITLE
cmd redirection not working properly with pipes

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#96]
``` sh
# works
json <= -aws ec2 describe-vpcs --vpc-id $vpcId >[2=]

# do not ..
json <= -aws ec2 describe-vpcs --vpc-id $vpcId >[2=] | xargs echo -n
```

**Comment by tiago4orion** [comment]
Duplicate of #71

**Comment by tiago4orion** [comment]
It's not duplicated. It is another pokemon class.

**Comment by vitorarins** [comment]
@tiago4orion I think this was fixed by #172

**Comment by tiago4orion** [comment]
I don't think so. I can still reproduce here

**Comment by tiago4orion** [comment]
correct send stderr to /dev/null: ```go build -h >[2=]```
do not redirect stderr: ```go build -h >[2=] | grep build```

**Comment by tiago4orion** [comment]
easy to fix: https://github.com/NeowayLabs/nash/blob/master/internal/sh/shell.go#L951
cmd's stderr being overwriten in pipe execution.
